import SwiftUI

/// Game version information model
/// Used to store and manage game version-related information, including startup configuration, etc
struct GameVersionInfo: Codable, Identifiable, Hashable {
    /// Game version unique identifier
    let id: String
    
    /// Game name
    let gameName: String
    
    /// Game icon path or URL
    let gameIcon: String
    
    /// Game version number
    let gameVersion: String
    
    /// Mod version number
    var modVersion: String
    
    /// Mod JVM parameters
    var modJvm: [String] = []
    
    var modClassPath: String
    
    /// Resource index version
    var assetIndex: String
    
    /// Mod loader type (e.g. Forge, Fabric, etc.)
    let modLoader: String
    
    /// last play time
    var lastPlayed: Date
    
    /// Java runtime environment path
    var javaPath: String
    
    /// Customize JVM startup parameters
    var jvmArguments: String
    
    /// Game start command
    var launchCommand: [String]
    
    /// Running memory size (MB)
    var xms: Int
    var xmx: Int
    
    var javaVersion: Int
    /// Game Main Class (Main Class)
    var mainClass: String
    
    /// Launch parameters (such as --launchTarget forge_client, etc.)
    var gameArguments: [String] = []
    
    /// Environment variable settings
    var environmentVariables: String
    
    /// Initialize game version information
    /// - Parameters:
    ///   - id: game version ID, a new UUID is generated by default
    ///   - gameName: game name
    ///   - gameIcon: game icon path
    ///   - gameVersion: game version number
    ///   - modVersion: Mod version number
    ///   - modJvm: Mod JVM parameters, default empty string
    ///   - modClassPath: Mod Classpath parameter, default empty string
    ///   - assetIndex: resource index version
    ///   - modLoader: Mod loader type
    ///   - lastPlayed: last play time, default is current time
    ///   - javaPath: Java path, default empty string
    ///   - jvmArguments: JVM parameters, default empty string
    ///   - launchCommand: launch command, default empty string
    ///   - runningMemorySize: running memory size (MB), default 2048
    ///   - resources: game resource list, default empty array
    ///   - mainClass: game main class, default empty string
    ///   - gameArguments: startup parameters, default empty array
    ///   - environmentVariables: environment variables, default empty string
    init(
        id: UUID = UUID(),
        gameName: String,
        gameIcon: String,
        gameVersion: String,
        modVersion: String = "",
        modJvm: [String] = [],
        modClassPath: String = "",
        assetIndex: String,
        modLoader: String,
        lastPlayed: Date = Date(),
        javaPath: String = "",
        jvmArguments: String = "",
        launchCommand: [String] = [],
        xms: Int = 0,
        xmx: Int = 0,
        javaVersion: Int = 8,
        mainClass: String = "",
        gameArguments: [String] = [],
        environmentVariables: String = ""
    ) {
        self.id = id.uuidString
        self.gameName = gameName
        self.gameIcon = gameIcon
        self.gameVersion = gameVersion
        self.modVersion = modVersion
        self.modJvm = modJvm
        self.modClassPath = modClassPath
        self.assetIndex = assetIndex
        self.modLoader = modLoader
        self.lastPlayed = lastPlayed
        self.javaPath = javaPath
        self.jvmArguments = jvmArguments
        self.launchCommand = launchCommand
        self.xms = xms
        self.xmx = xmx
        self.mainClass = mainClass
        self.gameArguments = gameArguments
        self.javaVersion = javaVersion
        self.environmentVariables = environmentVariables
    }
}
