import Foundation

/// Server address information model
struct ServerAddress: Codable, Identifiable, Hashable {
    /// Server unique identifier
    let id: String
    
    /// Server name
    let name: String
    
    /// Server address (IP or domain name)
    let address: String
    
    /// Server port (optional, default 25565)
    let port: Int
    
    /// Whether to hide the server icon
    let hidden: Bool
    
    /// Server icon resource location (optional)
    let icon: String?
    
    /// Whether to accept text to chat
    let acceptTextures: Bool
    
    /// Initialize server address information
    /// - Parameters:
    ///   - id: server ID, a new UUID is generated by default
    ///   - name: server name
    ///   - address: server address
    ///   - port: server port, default 25565
    ///   - hidden: whether to hide, default false
    ///   - icon: server icon, default nil
    ///   - acceptTextures: whether to accept textures, default false
    init(
        id: String = UUID().uuidString,
        name: String,
        address: String,
        port: Int = 25565,
        hidden: Bool = false,
        icon: String? = nil,
        acceptTextures: Bool = false
    ) {
        self.id = id
        self.name = name
        self.address = address
        self.port = port
        self.hidden = hidden
        self.icon = icon
        self.acceptTextures = acceptTextures
    }
    
    /// Get the complete server address (including port)
    var fullAddress: String {
        "\(address):\(String(port))"
    }
}
